### ISSUE TITLE
isServer is not defined

### ISSUE THREAD

**Issue by nwaughachukwuma** [jefrydco/nuxt-pwa-vuetify-starter#1]
Hi @jefrydco am getting following error: ReferenceError: isServer is not defined when I `npm run dev` my application. I don't really know what the error implies, and any help would be appreciated.

**Comment by mickaelicoptere** [comment]
same here

**Comment by nwaughachukwuma** [comment]
Hi @mickaelicoptere I was able to solve the problem by adding isServer as a parameter to extend, like so: 

  ```
extend (config, { isDev, isClient, isServer }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
      if (isServer) {
        config.externals = [
          nodeExternals({
            whitelist: [/^vuetify/]
          })
        ]
      }
    } 
```

**Comment by jefrydco** [comment]
@nwaughachukwuma @mickaelicoptere Sorry for late reply, thanks for pointing me on this. That was my bad, I'll resolve it soon.
